# Generated by Django 5.1.1 on 2024-10-05 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_item_alter_feeding_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
